name: simpy_example
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7.11
  - pip:
    - simpy==4.0.1
    - azureml-defaults==1.34.0
    - azure-cli-core==2.28.1
    - azure-core==1.18.0
    - azureml-core==1.34.0
